version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/x86_64
    container_name: notice-latest-program-version-app
    ports:
      - '8080:8080'
    env_file: .env
    stdin_open: true
    tty: true
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: 'redis:6.2'
    container_name: notice-latest-program-version-db
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
    env_file: .env
    networks:
      - backend

networks:
  backend:
    driver: bridge
